version: '3.2'

services:
  dapptools:
    restart: unless-stopped
    image: vulcanize/dapptools:v0.29.0-statediff-0.0.6
    environment:
      DB_USER: vdbm
      DB_NAME: indexer
      DB_HOST: indexer-db
      DB_PORT: 5432
      DB_PASSWORD: password
    ports:
      - "127.0.0.1:8545:8545"
#      - "127.0.0.1:8546:8546"

  migrations:
    restart: on-failure
    depends_on:
      - indexer-db
    image: vulcanize/statediff-migrations:v0.3.0
    environment:
      DATABASE_USER: vdbm
      DATABASE_NAME: indexer
      DATABASE_HOSTNAME: indexer-db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password

  indexer-db:
    restart: unless-stopped
    image: postgres:10.12-alpine
    environment:
      - POSTGRES_USER=vdbm
      - POSTGRES_DB=vulcanize_public
      - POSTGRES_PASSWORD=password
    volumes:
      - indexer_db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:8069:5432"

  indexer-graphql:
    restart: unless-stopped
    depends_on:
      - indexer-db
    image: vulcanize/postgraphile:v1.0.1
    environment:
      - PG_HOST=indexer-db
      - PG_PORT=5432
      - PG_DATABASE=indexer
      - PG_USER=vdbm
      - PG_PASSWORD=password
      - SCHEMA=public,eth
    ports:
      - "127.0.0.1:5000:5000"

  watcher-db:
    restart: unless-stopped
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_public"
      POSTGRES_PASSWORD: "password"
    command: ["postgres", "-c", "log_statement=all", "-N", "500"]
    volumes:
     - contract_watcher_js_db_data:/var/lib/postgresql/data
    ports:
     - "127.0.0.1:8070:5432"

volumes:
  contract_watcher_js_db_data:
  indexer_db_data:
